### ISSUE TITLE
Can't install on linux

### ISSUE THREAD

**Issue by lupa18** [golemfactory/clay#1126]
I downloaded package as it says in Wiki, then cd to the extracted folder and run: 
```
golem-0.6.0 $ sudo ./golem.sh --gui
sudo: ./golem.sh: orden no encontrada
```
So doesn't work.

**Comment by maaktweluit** [comment]
Try this:
`$ sudo ./golemapp`

Gui seems on by default, when running headless use `--nogui`

Will also have a look if i can add this to the wiki

**Comment by devonhk** [comment]
I can't install on linux either (ubuntu 16.04). I have docker installed and I ran the golemcli as root.

**Steps to repro**
1. Download https://github.com/golemfactory/golem/releases/download/0.6.0/golem-linux_x64-0.6.0.tar.gz
2. Extract 
3. run `sudo ./golemcli`

**Expected behavior**
Something happens...

**Actual behavior**
Nothing happens. A verbosity `-v` option would be nice to see what this binary blob is doing.

**Comment by mfranciszkiewicz** [comment]
The command line interface requires a running instance of `golemapp`.

For Ubuntu, I suggest downloading and running the [installation script](https://raw.githubusercontent.com/golemfactory/golem/develop/Installer/Installer_Linux/install.sh).
