### ISSUE TITLE
Fix adding a task

### ISSUE THREAD

**Issue by banasiakadam60** [golemfactory/clay#1294]
Drag&drop works fine, but adding task with a `+` button works horrible. It should somehow allow user to select file or directory. At this point it only allows to add a directory. First of all it's awful UX: we want to add a file, so we're going through some folders and realize, that we don't see a `.blend` file. And what is worst, we have a problem if we have more than one file in selected directory.
So we have to change it to

- Allow user to add file or folder

- Make it more intuitive and clear for user

**Comment by mdtanrikulu** [comment]
As I noted into [the code](https://github.com/golemfactory/golem-electron/blob/7374e299e3df91dc137e0035453f73b67625bfa3/src/components/Header.js#L156-L158);

It's a limitation from Electron. 

> Note: On Windows and Linux an open dialog can not be both a file selector and a directory selector, so if you set properties to ['openFile', 'openDirectory'] on these platforms, a directory selector will be shown.

For Mac users everything is okay but for Windows/Linux it doesn't support both (file and/or folder choose). If we'll choose one instead of other, opinions are welcome.

**Comment by jiivan** [comment]
The most popular solution to this problem is making to buttons: one a fileSelector and second directorySelector. I don't see any other way to make it user friendly. Both dialogs can use the same callback (`onFileHandler`).
