### ISSUE TITLE
Detect and display information that golem app is in the old version

### ISSUE THREAD

**Issue by badb** [golemfactory/clay#1295]
Necessary step to implement:
(1) Add app checking function in monitor, that send back info, if there is newer version of golem available. 
(2) Implement check in golem and pubsub to interface,
(3) Implement notification in the graphical interface with warning.

**Comment by Elfoniok** [comment]
Couple of question
1) How this function should check if newer version is available? Could it be written in some monitor resource file?
2) Does this step necessary? Gui could ask for this information monitor itself without core assistance.
3) So where and when? Like this should be periodically? Once for a change? This could be a popup? I could propose, that this check could be periodically but instead of showing warning popup, this could be a label below current version of installed application. So we could have:
Current version 0.8.1
Latest available version: 0.9.0

**Comment by Elfoniok** [comment]
Moreover it looks like this is a duplication for existing PR:
https://github.com/golemfactory/golem/pull/1447

Doesn't getting latest version from github is better option? Asumming that we always use github for our project.
