### ISSUE TITLE
Check if it's need to pass Task to LocalComputer instance. 

### ISSUE THREAD

**Issue by badb** [golemfactory/clay#1354]
https://github.com/golemfactory/golem/pull/1278/files#diff-a9bb404f61dccb6b7c3dfafee919ba9eR33
Probably this task is only used to get access to one function that may be passed with different methods. To be checked.

**Comment by inexxt** [comment]
`LocalComputer` shouldn't require `task` parameter. It is an inconvenience when doing verification, since there are no separate classes for verification tasks, and instead some code which gives `ComputeTaskDef` is provided (along with code run inside `LocalComputer` container). 
`task` is needed only when optional flag `use_task_resources` is set - it would make sense if instead of setting this flag to `True`/`False`, user would set it to `Task`/`None`.

`task` parameter is also used in `TaskTester`, when the method `after_test` is called - it should be easily refactorable too.
