### ISSUE TITLE
Limit number of tasks send in MessageTasks

### ISSUE THREAD

**Issue by badb** [golemfactory/clay#1463]
Right now nodes should send all the tasks that are known to it in MessageTasks. We should define a specific limit of maximum taks that are sent in one message. 

- [x] Propose a sensible limit (check how big is single message)
- [x] Choose an honest message cutting mechanism. Suggested methods: random, round robin. 
- [x] Implement chosen algorithm & limit in Golem

**Comment by Elfoniok** [comment]
MessageTask compose of 244 bytes of overhead, which is constant.
For each entry it yields on average 943 bytes (for each task header sent within)

We could gain here quite a lot, because a lot of data in TaskHeader is not used by remote node. Another task would be to analyze this and get rid of obsolete fields during serialization.

**Comment by Elfoniok** [comment]
https://github.com/golemfactory/golem/pull/1489
