### ISSUE TITLE
Installation from source on Mac needed

### ISSUE THREAD

**Issue by ederenn** [golemfactory/clay#1500]
There are no installing instructions from source on mac in Golem Factory wiki. It should be provided. Every required step should be written down, with illustrating print screens; commands used for installation as well included. Links from installation sites eg. homebrew listed and included in the sequence of installation. 
Installation instructions should be published on golem factory wiki

https://github.com/golemfactory/golem/wiki

**Comment by ederenn** [comment]
under installing instructions there should be provided information how to uninstall recent version

**Comment by gborowik** [comment]
https://github.com/golemfactory/golem/wiki/Installation-from-source-on-macOS

**Comment by maaktweluit** [comment]
Reviewed the script ( did not test ), only some small question:

- Is `python` the right version of python or should it be `brew install python3`?
- Should `docker-machine start golem` be called ( instead of `env` without eval ) before loading the env?

Also most commands are once, only `docker-machine start` and `eval $(docker-machine env)` need to be run each time after computer restart, maybe this can be split.

For the rest it is super clear and look good :)

**Comment by gborowik** [comment]
@maaktweluit 
1. corrected (when I tested I did `brew install python3`, however, did not correct the info). 
2. when docker is created by a user it starts automatically, however, after a system restart (who is restarting macOS:) ), it should be loaded again. I have split the lines.

Thanks for those remarks.

Please check.

**Comment by maaktweluit** [comment]
Since #1487 `qt` is no longer a dependency

**Comment by gborowik** [comment]
Sure, removed.

**Comment by maaktweluit** [comment]
LGTM!
