### ISSUE TITLE
build-images.sh returns error if there are some files to which it doesn't have access

### ISSUE THREAD

**Issue by badb** [golemfactory/clay#152]
If in Golem directory there is a file which cannot be copied (eg. no read access) than script end up with an error.

**Comment by badb** [comment]
This issue may no longer be valid, we should check if problem still occurs.

**Comment by banasiakadam60** [comment]
This bug is still valid. On github I found discussion about this issue (https://github.com/docker/docker/pull/6644). There was a proposal to add flag, which allow to ignore such files, but it wasn't accepted. So all we can do is to inform user about files with unallowed permissions and ask him to move/remove them, or we can force user to run this script with sudo and then move such files to some temp dir, like ~/.golem_tmp and when script will finish its work, restore files and remove tmp.
I propose to print some message about such files and then move them to tmp.
@badb what do you think?

**Comment by badb** [comment]
Hm, so it's a feature not a bug :) It was more of a problem befor when tests used to left some unwanted files inside repo. Running with sudo and moving files doesn't sound like a good idea. I'd suggest we ignore it. 
Can you just add a comment [here](https://github.com/imapp-pl/golem/wiki/Testing-with-IMUNES) that build.sh only works if repo directory is clean, ie user has access to all files?

**Comment by banasiakadam60** [comment]
Done :) Closing this issue.
