### ISSUE TITLE
Task computing error, exit code 137

### ISSUE THREAD

**Issue by ederenn** [golemfactory/clay#1646]
``` 2017-11-09 14:21:52 ERROR    golem.task.taskthread               b'Task computing error: Subtask computation failed with exit code 137'```

appeared on windows, source version
received during testing Configuration changes, windows and mac were connected with each other.
Task was uploaded on Mac, windows was computing task. 
Task: bmw file, 3600x2400, 1frame, 30 min task, 5 subtasks - 10 min
error appeared after committing the task and before changes in configuration.
Previous to that task, other tests with configuration changes were conducted and finished.

**Comment by etam** [comment]
Looks like it (a subtask) was killed by OOM (Out-Of-Memory) Killer.

**Comment by etam** [comment]
I think there's nothing to be done. This happened, because the computation required high amount of memory, and it reached the limit. It's something that will happen in real life.

The question is, was it reported to requestor and properly handled?

You can try to reproduce this by reducing the amount of memory of the provider.

**Comment by etam** [comment]
We can also detect "exit code 137" in message and append "probably killed by out-of-memory killer" to the log.
