### ISSUE TITLE
Messages failing to be verified

### ISSUE THREAD

**Issue by etam** [golemfactory/clay#1799]
~~In Hello message there is a `rand_val: float` that is supposed to be signed by the other node. The problem is that a float cannot be trusted.~~

```
2017-12-21 14:10:15 INFO     golem.network.transport.session     Failed to verify message signature (RandVal(timestamp=1513861815.886788, encrypted=True, sig=b'...', slots=[['rand_val', 0.4781411593100001]]) from 10.30.10.95:40103)
```
~~As seen above, the float value got additional `00001` at the end and the verification failed.~~

**Comment by Krigpl** [comment]
This error - `Failed to verify method signature` - isn't connected to the value of RandVal, it checks the signature and doesn't look at the rest of the message. Here it would mean that the RandVal message has been incorrectly signed, but it could happen to any other message as well.

While I agree floats cannot be trusted in general, the problem here is of a different nature. You don't know the original value of `rand_val` so you can't tell whether `00001` was "additional". Please rename this issue and ideally provide more details next time you see it (like pub/priv keys of the sender node and the signature itself).

**Comment by Krigpl** [comment]
This is happening to me consistently with other message types as well
```
INFO     [golem.network.transport.session    ] Failed to verify message signature (Peers(timestamp=1514454880.48068, encrypted=True, sig=b'P?\x11\x89\xfa9\x94\x91\x18\xc6\x16\xe4g\xa9\x95`\x13\xb0\xf7r\xe94B6\xc9\n\xba\xf5\xf3w\xc8e\x1c\xdc\xfc\xa5\x0b\n\x19z_<\x95\x0e\xdd\xcb+A\x870+\xeb\xc5#\x80\x82\xa1s\xb9B\x1e\xf5\x99y\x00', slots=[['peers', [{'node': <golem.network.p2p.node.Node object at 0x7fd96034b278>, 'port': 40103, 'id': 'f6a48d728cb05d53fd30fa96f67f2353aa7641576ddbc3991605554f9a279566bff97f064485c4c0aae65aec17b2bc294b6dced73338947df1ff0ade4ae6b78d', 'address': '10.30.10.101', 'node_name': 'igor'}]]]) from 127.0.0.1:56770)
```

I believe this is regression introduced by https://github.com/golemfactory/golem-messages/commit/c90519a79e47a08f7a6195e4ad38d2914df496e2
I checked a commit before this one and it doesn't reproduce.
Passing to @jiivan to investigate.

**Comment by jiivan** [comment]
Do you know the sources of incorrectly signed messages? It is probably related to incompatible versions of golem-messages. Yes, the signing function was updated in https://github.com/golemfactory/golem-messages/pull/51

Also note that this PR https://github.com/golemfactory/golem-messages/pull/58 adds `__version__` attribute to golem-messages lib & could make it possible for nodes to compare library versions. A review would be greatly appreciated. :)

Closing it for now. Please reopen if new facts uncover.

**Comment by Krigpl** [comment]
You can reproduce it using two local nodes with the same golem-messages version, so nope, this isn't related to incompatible versions.
Please close the issues only *after* checking (yourself or confirming with the reporting person) the issue has been resolved.
