### ISSUE TITLE
missing hyperg logs

### ISSUE THREAD

**Issue by ederenn** [golemfactory/clay#1828]
Windows vm, binaries 0.10.1
creating HyperG logs stopped for no reason

Golemapp was running, one task ended in timeout
next small task was added, timeout set for 15 min
after more than hour task was stil in preparing state
checked in golemcli task was "not started"
checked in HypeG logs - for that task they were never created
added next task, and checked HyperG logs if next task created logs
logs for next task weren't created, this task ended hanging in preparing state as well
interface of an app is working

after reopening the app window tasks are still in preparing and not ending in timeout but new logs in HyperG were created - with timestamp after reopening

**Comment by mfranciszkiewicz** [comment]
The task was stuck in the "Preparing" state because an API request to add resources to HyperG was never sent. This issue is caused by a congested event loop and can be solved by migrating from HTTP requests sent in `deferToThread` to using Twisted's `Agent` (https://github.com/golemfactory/golem/pull/1816)
