### ISSUE TITLE
[ERR] tETH Faucet Error code 403

### ISSUE THREAD

**Issue by kascheri12** [golemfactory/clay#1829]
On Windows 0.10.0 binary. 

```
2017-12-29 22:40:49 INFO     golem.pay                           b'ETH: 0.00901288 '
2017-12-29 22:40:49 INFO     golem.pay                           b'Requesting tETH '
2017-12-29 22:40:50 ERROR    golem.ethereum                      b'tETH Faucet error code 403 '
```

**Comment by Krigpl** [comment]
This isn't a bug. We are using https://github.com/locals-world/locals-faucetserver for our faucet server and as you can see error code 403 means that the queue is full, but might become available later. (but I definitely agree that returning error code 403 doesn't look friendly for non actual error)
This issue become more common recently since the demand increased and our faucet is constantly under high load, I'll see what we can do here.
Removing the `bug` tag though.

**Comment by Krigpl** [comment]
Mitigated the issue so it happens less often, but we can't resolve it completely at the moment.
