### ISSUE TITLE
Task estimation time

### ISSUE THREAD

**Issue by chriscrutt** [golemfactory/clay#1843]
Although I have a very small file, I was playing around and set task and subtask timeout to 80 days. Obviously it wouldn't take that long to render a small file. I also set the subtask amount to 10 although I wouldn't need it. Lastly my bed was 1 GNT/h.

My estimated price is 1.92*10^4 GNT... seems reasonable if you think it would take the entire 80 days... but its not. 

In the future maybe there could be something which checks file sizes and how many people are offering computing power and the bid and etc.

also what happens if I run out of GNT when someone's rendering my stuff...? cause the way I see it is like a taxi cab. The driver doesn't know how much money you have until you pay... hopefully I'd have enough but mistakes happen.

**Comment by maaktweluit** [comment]
Hey @chriscrutt 

Thanks for the feedback!

There are 2 sides to this:
- Estimation before starting ( related to #823 )
- Payments 
  - Ensure you have enough when starting
  - Ensure you have enough when finished
  - Pay per second of computing

I think Golem should check before requesting any task if the worse case scenario can be payed for, excluding already running tasks and they're worse case estimates.

Since i'm not sure i will check with the team and get back to you on the payments side.

Have a good one!

**Comment by maaktweluit** [comment]
Spoke to the team on payments:
The taxi scenario should never happen, currently Golem checks before starting a task like i described.

The payments are currently based on the timeout, not the time spend. There are a lot of edge cases and trust issues to make this better, not sure if this will be picked up before the Brass release.

Hope this answers all your questions, if not feel free to re-open the issue or join the discussion on chat.golem.network. You can tag me on the same username.

**Comment by chriscrutt** [comment]
yeah you definitely helped, thanks!
