### ISSUE TITLE
Cleanup usage of Defaults classes in Apps

### ISSUE THREAD

**Issue by badb** [golemfactory/clay#2428]
We have TaskDefaults class and all the classes that inherits from it, ie. BlenderDefaults, LuxRenderDefaults, etc. They were used in old GUI, but are probably ignored in the new one. They are partially used in building task definition from dictionary, but not all fields are included. 
We should clean usage of these classes and make its function more explicit.

**Comment by inexxt** [comment]
It appears that they are indeed used mostly in tests:
 - for `dummytask`, defaults are used to build test task for benchmark, but the benchmark isn't used anywhere
 - for `renderingtask`, only two fields are used, `defaults.min_subtasks` and `defaults.max_subtasks` - and used input is checked against them (which doesn't make much sense IMO, since they should be *default* values, not *limiting values*. In other words, removing them from here would make things better. The same situation happens in `framerenderingtasks.calculate_subtasks_count`, although it also uses `defaults.default_subtasks`.
 - `luxrendertask` doesn't use them, except for the inherited method of `renderingtask`. In particular,`main program_file` is not used anywhere (everything uses `LuxEnvironment.main_program_file` directly)
 - `blendertask` - as above.
 - for `coretask`, defaults in construction of `CoreTaskBuilder.build_minimal_definition`, to get `main_program_file`.
 - `TaskTypeInfo.defaults` are only used to do the thing above

So, it seems refactor should be relatively easy, except for the question where to store `default/min/max subtasks`.

@badb ?

**Comment by badb** [comment]
Let's have a class method `get_param_limits` that return dictionary with param name and a pair of (min, max). It should be universal enough and later used by GUI.
