### ISSUE TITLE
SubtaskState.subtask_rem_time is always 0

### ISSUE THREAD

**Issue by Wiezzel** [golemfactory/clay#2562]
It is set to zero:
https://github.com/golemfactory/golem/blob/develop/golem/task/taskstate.py#L52
And updated to zero:
https://github.com/golemfactory/golem/blob/develop/golem/task/taskmanager.py#L465
https://github.com/golemfactory/golem/blob/develop/golem/task/taskmanager.py#L522

But never really updated.

**Comment by tworec** [comment]
@jiivan we should also remove ETA from CLI
https://github.com/golemfactory/golem/blob/f9413f940a858bd142e2e0c34e9c7ac6882bffd6/golem/interface/client/tasks.py#L121


@Wiezzel its better to use permalink like this
https://github.com/golemfactory/golem/blob/a15b359e93376c432d46b3573c5d072c2b0020c0/golem/task/taskstate.py#L52

because it will always be valid, and your links in this issue description are pointing now semi-randomly

this is how to get permalink
![image](https://user-images.githubusercontent.com/12720209/57609474-40c54300-756f-11e9-8a7e-f2f401962d47.png)

**Comment by Wiezzel** [comment]
@tworec Yep, now I know this. But the issue is 1 year old... :stuck_out_tongue:
