### ISSUE TITLE
Tips and hints for new implementations

### ISSUE THREAD

**Issue by fbsanches** [golemfactory/clay#2603]
1. Add two-factor authentication as per email, sms or authenticator.
2. Add short self-explanatory help balloons to make it easier on the application settings and their handling.
3. Add auto-start feature when booting the system and / or restarting the application if it is too idle.

**Comment by badb** [comment]
@fbsanches Hi, thank you for suggestions!

1. Won't be possible because we're decentralized application and we don't want to include centralized double authentication methods. 
2. We've already added some tips, but if you find some settings where they are still missing let us know. Also if you suggest adding something more fields to onboarding, please specify which one. 
3. We're adding auto-start on variou OSs to the backlog!
