### ISSUE TITLE
Option to start Golem in the background after login

### ISSUE THREAD

**Issue by mikalehmann** [golemfactory/clay#2615]
This feature request is actually made up of two features that are needed for this:
1. A way to minimize Golem to the tray.
2. An option to add Golem to startup. This is possible right now but most users don't know how to add programs to Startup.

I'm using the Windows version, but this might also apply to Mac and Linux.

**Comment by Brblol** [comment]
+1

**Comment by sifotes** [comment]
In addition to adding a "minimize on close" option, adding a confirmation message when closing would be helpful.

**Comment by Brblol** [comment]
It should also not ask for a password when it starts up. Maybe it should ask for a password only for certain operations like configuration changes or withdrawals

**Comment by ghost** [comment]
Start off by saying my comments and views do not reflect or represent Golem.

Are you saying this application should not do something? Did you design and create this application? In REFERENCE to the Comment  (((It should also not ask for a password when it starts up. Maybe it should ask for a password only for certain operations like configuration changes or withdrawals__+_) One question after do you want anyone to have the ability to transfer your ETH or GNT where they want?  Do you have a Blue icon on your whatever mac users call their GUI? Its round and says Docker in their somewhere. Click that or whatever you call it on a MAC. Or read instructions TTS works on MACS too right so you can listen instead of read.
Qanon1111

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by mikalehmann** [comment]
>Did you design and create this application?

You can see the answer to that in Brblol's profile.

> One question after do you want anyone to have the ability to transfer your ETH or GNT where they want?

"for certain operations like configuration changes or withdrawals" implies that security is still preserved. Please don't ask leading questions, especially when they have already been answered.
