### ISSUE TITLE
Rendered and finished task not copied to destination

### ISSUE THREAD

**Issue by ktomala** [golemfactory/clay#2645]
From the requestor side after finishing rendering task which by default has .JPG output, the finished rendered image is not copied over to the destination directory. 

Example scene: zuendholz_forest.blend

**Comment by Elfoniok** [comment]
During local test, when default parameters should be recognized, when scene has default jpg format, we fail to recognize this (probably because we drop support for jpg outputs?). This results in not "Not Loaded" in `Fromat` editbox. However despite this, GUI is sending "jpg" as demanded format, which is wrong since Blender is using `JPEG` which is the same, but has to be formed with `e`.

We should:
1. Decided what to output in case we don't support some output format during local tests.
2. Send to core valid output type format
3. Return some error if we still don't support type which GUI sent.
