### ISSUE TITLE
Add proxy settings to golem client

### ISSUE THREAD

**Issue by Slavenin** [golemfactory/clay#2744]
Hi, all! In Russia due to try block telegram blocked 18kk ip adresses. Golem geth ip too! See https://github.com/golemfactory/golem/issues/2686#issuecomment-384257737 as example. And use golen without vpn imposible. Please add proxy settings in client, that proxy traffic to tor or other network.
Regards.

**Comment by ghost** [comment]
I told you this would happen. Hello do you know how to setup DNS quad 9 or 1.1.1.1. IAM the one who informed there would be issues with the remote and submitted bug reports on issues but was told it wasn't a security risk. And I wasn't eligible for bug contest. Well my issue nOw is that I have a consistent 9 to 10 nodes using thousands of MB of Data while my provider and requestor settings are at 100. I want to know why these nodes are using my resources and I haven't received any compensation this is the second time I have emailed about this. I looked at my usage on the virtual host only and it was at 1 petabyte. What is the deal how will anyone except these nodes get to my system to render if it is full of individuals using my resources to do God onows what. I do not understand the concept but I bet singularity net will figure it out. I have one GNT in my golem wallet and have been running consistent since mainnet became available.

Sent from ProtonMail mobile

-------- Original Message --------
