### ISSUE TITLE
Can not use macos Golem

### ISSUE THREAD

**Issue by Petelin** [golemfactory/clay#2751]
it block me at terms, click accept is nouse, there is a yellow warning on the top : "interface communication problem with golem".
but i can goto internet, what's wrong?

**Comment by Petelin** [comment]
seems it is because i do not have public ip address

**Comment by badb** [comment]
Hi @Petelin 
Public ip address is not required if you are able to forward ports / have upnp enabled in their router. 
This error means that there is no communication between golem core and GUI which may be caused by too heavy computation or some problems with Golem core. 

Please check this site: https://golem.network/documentation/09-common-issues-troubleshooting/ and if you can't find solution there ask for help on Rocket chat (https://http://chat.golem.network).
