### ISSUE TITLE
Terms button!

### ISSUE THREAD

**Issue by Warolf** [golemfactory/clay#2780]
Hi, 

I can't acept the terms!
The button does not work!
<img width="426" alt="captura de ecra 2018-05-16 as 21 03 26" src="https://user-images.githubusercontent.com/5637034/40141111-b44b9d6e-594c-11e8-871e-bc6f52a21bc4.png">

**Comment by badb** [comment]
Hi @Warolf! It usually means that there are other problems with your golem instance usually caused by Docker problems. Please check the steps described here: https://golem.network/documentation/09-common-issues-troubleshooting/ 

If nothing helps, then please send us logs https://golem.network/documentation/15-understanding-logs/  to contact@golem.network or join Rocket Chat to get some help in real time (https://chat.golem.network).
