### ISSUE TITLE
Investigate golemcli performance issues

### ISSUE THREAD

**Issue by shadeofblue** [golemfactory/clay#3014]

**Comment by ktomala** [comment]
The cause for big slowdown is because of unzipping of archive contents inside EXE created by PyInstaller every time golemapp and golemcli starts.

Recommended approach is to change .spec files from utilizing onefile option changing it to onedir.
This can be done by changing .spec file like this:

```
pyz = PYZ(a.pure,
          a.zipped_data,
          cipher=block_cipher)

exe = EXE(pyz,
          a.scripts,
          exclude_binaries=True,
          name='golemapp',
          debug=False,
          strip=False,
          upx=False,
          icon=icon,
          console=True)

collect = COLLECT(exe,
                  a.binaries,
                  a.zipfiles,
                  a.datas,
                  strip=None,
                  upx=False,
                  name='golemapp')
```

This also will probably need adjusting buildbots and advanced installer.
