### ISSUE TITLE
Transfer GNR to GolemApp

### ISSUE THREAD

**Issue by badb** [golemfactory/clay#307]
New plan:
![634e52a4-ac3b-11e6-970a-4935a7e44585](https://cloud.githubusercontent.com/assets/483392/20709182/09197cf2-b634-11e6-8019-98ec076c9a53.png)

**Comment by chfast** [comment]
My suggestion is:
- `golem` - core Golem libraries used to build applications,
- `golemapp` - Golem App (currently for rendering),
- `golemapp.ui` - UI components.

Alternatively, using Python namespace packages (top level package must be empty):
- `golem.core`,
- `golem.app`,
- `golem.ui`.

I think there should be no rush to change that. And in my opinion it doesn't make sense to make all components super reusable and generic. I would prefer having very simple UI that can be easy changed instead of set of plugins and customizers.

**Comment by badb** [comment]
I think I prefer the first one. 
And how can we organize  tasks / plugins?  Should we keep it as it is now, with general directories that keeps different parts of task, ie:
- `task` where we keep tasks logic,
- `ui` where we keep task specific widgets,
- `customizers` where we keep widgets' logic,
- `scripts` where we keep executable code?
  Or alternatively we may keep all task related components in separate director, eg. `blender` directory containing files like `widget.py`, `customizer.py`. Maybe it will make adding new tasks easier.

**Comment by chfast** [comment]
This is all about `golemapp` right?

So the layout looks ok, but I would move `scripts` under `tasks`.

Plugin based layout seems to be better. Plugin should define a set of task templates with UI, scripts, environments. But we might want to get there in steps.
