### ISSUE TITLE
Problem with crop test - TestGenerateCrops

### ISSUE THREAD

**Issue by inexxt** [golemfactory/clay#3127]
`test_multiply_frames_in_subtask` in `tests.apps.blender.test_blender_reference_generator.TestGenerateCrops` often fails with timeout - e.g. here https://circleci.com/gh/golemfactory/golem/11025
(the tests from #3074, which doesn't deal with anything around generating crops).

**Comment by mkabdullahi** [comment]
May I suggest to try the testing using CircleCI 2.0 version? Because according to the two attached screenshots, I think this will helps with the **timeout error** 

![screen shot 2018-08-05 at 11 07 06 pm](https://user-images.githubusercontent.com/5393611/43690069-5789826a-9904-11e8-8cc9-6bdad365b02b.png)
![screen shot 2018-08-05 at 11 07 16 pm](https://user-images.githubusercontent.com/5393611/43690070-5c67f33e-9904-11e8-8f8b-42a6fa6ea710.png)

**Comment by Elfoniok** [comment]
First of all i am curious if have you encountered this on buildbot? Because we are dropping Circle CI. Nevertheless here is PR which will speed up test 3 times, so it should help.
https://github.com/golemfactory/golem/pull/3131

**Comment by inexxt** [comment]
No, on buildbot they were passing fine, and after merge they are passing locally too.
Closing.
