### ISSUE TITLE
Building docker images from setup.py fails

### ISSUE THREAD

**Issue by chfast** [golemfactory/clay#337]
There is base container missing.

```
Running 'docker build -t golem/blender -f scripts/Dockerfile.blender .' ...

Sending build context to Docker daemon 26.86 MB
Step 1 : FROM golem/base
Pulling repository docker.io/golem/base
Error: image golem/base:latest not found
Docker build failed: Command '['docker', 'build', '-t', 'golem/blender', '-f', 'scripts/Dockerfile.blender', '.']' returned non-zero exit status 1
```

**Comment by badb** [comment]
It's not missing. I guess the reason is that it takes the list of all dockerfiles and build containers in that order. It's usually alphabetic and `base` is before `blender` but the documentation claims that the result of `os.listdir` is `in arbitrary order.`. 
So. We can fix that easily "for now" by building base container first and put other containers in different directory but we should think how to make a good containers hierarchy in the future.

**Comment by badb** [comment]
https://github.com/imapp-pl/golem/pull/340 Is it ok for now? 
Until we will have a better environment manager.
