### ISSUE TITLE
 strings and ints confused in task definition

### ISSUE THREAD

**Issue by ederenn** [golemfactory/clay#3399]
#### Encountered on:
mainnet Mac OS, Linux, source, branch b0.18.0

during task creation, not possible to start a task on source b0.18.0
mainnet Mac OS, Linux, on cpu and gpu

task uploaded manually using GUI

```
ERROR    [golem.client                       ] Cannot create task {'resources': ['/Users/ederenn/Desktop/GPUvsCPU/Table_GPU.blend'], 'taskName': 'Table_GPU.blend', 'relativePath': '/Users/ederenn/Desktop/GPUvsCPU/Table_GPU.blend', 'name': 'Table_GPU', 'type': 'Blender', 'compute_on': 'cpu', 'timeout': '0:30:00', 'subtasks': '4', 'subtask_timeout': '0:10:00', 'bid': '0.2', 'estimated_memory': 343089152, 'options': {'resolution': [400, 400], 'frames': '1-10', 'format': '', 'compositing': False, 'output_path': '/Users/ederenn/Documents'}}: '<=' not supported between instances of 'int' and 'str'
```

**Comment by shadeofblue** [comment]
we need to add type casts to the task definition JSON

**Comment by etam** [comment]
Wild idea: implement validation using json-schema https://json-schema.org/

**Comment by kmazurek** [comment]
The problem here is caused by the field `subtasks` being parsed as a string instead of an int in golem core. This fails in: `Client#get_subtasks_count` for parameter `total_subtasks`.
I did not manage to reproduce this issue directly, only caused the same problem by hardcoding `subtasks` to be a string (or when trying to upload the task def file from CLI).
Will look further into this.

**Comment by kmazurek** [comment]
The task def JSON sent over by the electron app is already fixed (tested on latest versions of electron/core pair). I think it makes sense to add JSON schema validation and/or testing. I created a separate issue for it (#3600).
