### ISSUE TITLE
Write instruction for building taskcollector

### ISSUE THREAD

**Issue by badb** [golemfactory/clay#375]
We need a short instruction how to build a taskcollector (on Ubuntu and Windows). It should be added somewhere to this section: 

https://github.com/imapp-pl/golem/wiki/Installation#runing-from-the-source

**Comment by banasiakadam60** [comment]
At this moment FreeImage has a bug and the fix is needed to build it. This bug will be removed in next version of FreeImage, but we don't know when it will be released. I've prepared a small patch, to fix this, but we need to publish it somewhere. Do we have any public server, where I can put this patch?

**Comment by banasiakadam60** [comment]
I suppose this issue can be closed.
