### ISSUE TITLE
Start using golem.Client(geth_address)

### ISSUE THREAD

**Issue by jiivan** [golemfactory/clay#3758]
`geth_address` argument in `golem.client.Client` is unused by mistake. It should override default `EthereumConfig` value is provided.

**Comment by ANDREYDEN** [comment]
created a [solution](https://github.com/golemfactory/golem/pull/3760). If the only problem was deleting the argument...

Update: tests failed, I suppose that's because `golem.client.Client` is used in other files and the `geth_address` variable is set there. How can I get the structure of the project to know wich files to change?

P. S. I'm new to contributing

**Comment by Krigpl** [comment]
@ANDREYDEN Click on `details` link next to the failed tests then see what tests have failed - you'll get the filepath of the test then you should be able to find `Client` usage there and modify it appropriately.

**Comment by ANDREYDEN** [comment]
thank you! I will fix the issues.
Quick question: should I always re-run the tests to see what's wrong (because the run for 10 mins or so)? Is there a faster way?

**Comment by jiivan** [comment]
@ANDREYDEN you can try to run tests with `pytest --maxfail=5 -v --lf tests/`. This way pytest will only rerun previous failures.

**Comment by Krigpl** [comment]
@ANDREYDEN Sorry about the confusion but it turns out that `geth_address` not being used is a bug and instead it should override the default value from the config provided here https://github.com/golemfactory/golem/blob/develop/golem/node.py#L107
So we don't want to remove it after all, but start using again. If you don't mind changing your PR to reflect this, it'd be great.

**Comment by ANDREYDEN** [comment]
I'm not sure that I understand the problem... What should `geth_address` be used for?

**Comment by Krigpl** [comment]
Sorry, there's a bug in the code and the proper fix isn't just removing this argument. This doesn't qualify as a `good first issue` anymore as it is a bit more complicated and has to be fixed before the next release. Feel free to pick up another issue though :)
