### ISSUE TITLE
provider stats values not adding up (computed/accepted/errors)

### ISSUE THREAD

**Issue by shadeofblue** [golemfactory/clay#3872]

**Comment by jiivan** [comment]
1. Most important issue is the lack of message queue #2223 This causes that if due to temporary network issue task session can't be established it will be lost.
1. Subtask verification is started only when task session is established `TaskServer._add_pending_request(TASK_CONN_TYPES['task_verification_result'], ...) -> TaskSession.result_received()`
1. If any of callbacks fails (pulling package cbk upon _ReportComputedTask_ receival, verification cbks started in `.results_received`), no message will be sent to provider
