### ISSUE TITLE
max_price is ignored when creating new task

### ISSUE THREAD

**Issue by etam** [golemfactory/clay#3963]
In `ClientConfigDescriptor` there is a variable `max_price`. In `appconfig.py` it's described as "Default max price per hour". In `golem/interface/client/settings.py` it's described as "Max GNT/h price (requestor)".

This variable is only used by golem-electron, when setting default bid value. It's not used anywhere in golem. It is possible to set `max_price` to 0 and create a task via cli with bid > 0.

Possible solution: when creating task check if bid satisfies max_price and make it a failure if it's not.

**Comment by shadeofblue** [comment]
Do we really need to enforce such a limitation? both values are under requestor's control -> what sense does it make to force the user to update their settings just because they want to set a higher price for the task they're creating? ... I believe it's just a matter of naming -> it shouldn't be named `max_price` but rather `default_price`...

@jamuszyn opinion?

**Comment by etam** [comment]
The current name suggests that it's a limit, that a user puts on himself. And in this case this limit is not enforced.

If it's supposed to be just a default value, then sure, it's just a naming issue. Maybe `default_requested_price` would be better, to make it clear it's not used by provider. In this case it would also make sense to make `bid` value in task dict optional and fill it with value from config if it's missing.

// there are 2 hard things in IT: naming things, cache invalidation and off-by-one errors.
