### ISSUE TITLE
ubuntu 19.10 missing docker "eoan Release"

### ISSUE THREAD

**Issue by sirnicolas21** [golemfactory/clay#5026]
> $ sudo ./install.sh 
> Golem Linux Installer version 0.1.0
>  ⬝ Downloading manifest ✓
>  ⬝ Downloading install script for extension 'gvisor' ✓
>  ⬝ Downloading runsc ✓
>  ⬝ Downloading runsc hash ✓
>  ⬝ Checking runsc hash ✓
>  ⬝ Installing runsc ✓
>  ⬝ Downloading install script for extension 'linuxmint' ✓
>  ⬝ Downloading install script for extension 'nvidia' ✓
>  ⬝ Downloading nvidia-container-runtime Packages list ✓
>  ⬝ Adding nvidia docker repository GPG key ✓
>  ⬝ Downloading nvidia docker repository list ✓
>  ⬝ Adding nvidia docker repository ✓
> WARNING: Forcing installation: docker-ce=5:18.09.7~3-0~ubuntu-bionic
> WARNING:    required by: nvidia-container-runtime
>  ⬝ Adding multiverse repository ✓
>  ⬝ Removing obsolete docker ✓
>  ⬝ Installing docker dependencies ✓
>  ⬝ Adding docker repository GPG key ✓
>  ⬝ Adding docker repository ✕
> 
> Command returned errors:
> ------------------------
> Warning: apt-key output should not be parsed (stdout is not a terminal)
> E: The repository 'https://download.docker.com/linux/ubuntu eoan Release' does not have a Release file.
> 
> ERROR: Failed adding docker repository.

**Comment by maaktweluit** [comment]
Hey @sirnicolas21 ,

Thank you for reporting this issue!

We officially only support LTS ubuntu releases, but with a few manual tweaks it should work on newer versions too.

It seems docker-ce is not yet officially supported on ubuntu 19.10: https://docs.docker.com/install/linux/docker-ce/ubuntu/

![](https://user-images.githubusercontent.com/1804568/67424710-eed12080-f5d6-11e9-96bb-49aea3a51018.png)

There seems to be a work-around: https://github.com/docker/for-linux/issues/833#issuecomment-562837503
updating the release from `eoan` to `disco` works for some people. Have not tested this myself.

Closing the issue since it is known on the docker side. Feel free to re-open it or make a new issue when you run into anything else.

**Comment by aeiouknown** [comment]
I changed line 392 of the install script to:

`$( sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable" > /dev/null ) &`

and the script finished using Xubuntu 19.10 (with Nvidia).
