### ISSUE TITLE
Resource Handshake Error due to outdated Message Queue messages

### ISSUE THREAD

**Issue by mdtanrikulu** [golemfactory/clay#5105]
## Description

Due to the unexpected termination of Golem, old handshake messages in Message Queue hangs and this causes handshake issues for the further handshakes.

**Golem Version**: latest observation is in 0.22, but seen in previous versions as well.

**Golem-Messages version** 3.14.1

**Electron version** (if used): n/a

**OS** [e.g. Windows 10 Pro]: latest observation is on MacOS 10.14.6, seen in different OS'es as well.

**Branch** (if launched from source): b.0.22 and others

**Mainnet/Testnet**: tested on Testnet

**Description of the issue**:

While with clear installation everything is fine, after some time later node starts to struggle with handshake issues. Currently whenever I am going to create a task, unable to get a computation due to resource handshake timeout errors.

**Actual result**:

_What is the observed behavior and/or result in this issue_

## Steps To Reproduce

1. Launch Golem
2. Create a task and terminate the Golem in starting handshake step
3. Re-Launch the Golem
4. Create a task
5. From that moment you will have handshake timeout error in your node whenever you create a task.

## Expected behavior
Handshake should be successful

## Logs and any additional context
```
INFO     [golem.task.taskkeeper              ] Adding task 'decb15e8-549e-11ea-af5d-7c67a4b1777f' support=<SupportStatus ok ({})> 
INFO     [golem.task.server.resources        ] Starting resource handshake with '7c67a4b1..25b230ca' 
INFO     [golem.task.server.resources        ] Resource handshake timeout. node=7c67a4b1..25b230ca 
INFO     [golem.task.acl                     ] Banned node. node_id=7c67a4b1..25b230ca, timeout=7200s 
```

## Proposed Solution?
Golem should remove old handshake messages from the message queue before starting new handshake and handshake messages should have an expiration mechanism to be cleared out.

**Comment by mfranciszkiewicz** [comment]
@mdtanrikulu Counter proposal: implement a connectivity check within `simple-transfer` and remove current resource handshake logic from Golem. This way:

- timeouts are handled by an external process, independent of Golem's main event loop and no longer susceptible of timeouts due to event loop overloading (only result _handling_ is queued in the main event loop, not the timeouts themselves)
- we decrease the number of network messages exchanged within the Golem protocol

It should be enough to track connecting node ids (or some other kind of token) in `simple-transfer`, try to initiate a connection (which would _conditionally_ trigger a connection from the other side) and match the two in a given timeout period.

**Comment by mdtanrikulu** [comment]
@mfranciszkiewicz It look reasonable, but will require more time, work and test. I am all in favor of fixing the issue first with the upcoming release, which will improve success rate of the network I believe. Then we can start refactoring the existing structure as in your proposal. Thoughts?

**Comment by mfranciszkiewicz** [comment]
@mdtanrikulu I agree, though the new handshake can be worked on and tested independently of these changes
