### ISSUE TITLE
Blender advanced verification not working for small subtasks

### ISSUE THREAD

**Issue by magdasta** [golemfactory/clay#680]

**Comment by globatum** [comment]
@magdasta any updates on this?

**Comment by magdasta** [comment]
Sorry, not working at GolemFactory anymore

**Comment by badb** [comment]
This was partially solved, but there still may be some problems. We don't want to verify subtasks using samples that are smaller than 8x8 pixels. In fact, we don't want to allow users to define subtasks that may have height smaller than 8 pixels.
We want to define:
* minimum acceptable resolution (it should probably be bigger than 8 pixels - 64? 128? @Elfoniok please decide what is the resonable value)
* maximum number of subtasks that can be defined for given resolution. For example for task with resolution 800xX maximum number of subtasks should be 100, but for task with resolution 600xX maximum number of subtasks should be 75. 
This checks should be implemented for both GUI (@mdtanrikulu) and core (@Elfoniok).

**Comment by badb** [comment]
Related issue: #682 
Should also resolve: #2002

**Comment by Elfoniok** [comment]
Because our verification scheme is based on random crops which sizes are percentage of chosen dimension (y) they will grow, with resolution. Because of that this ratio is constant and yields percentage of dimension for single frame.

Since first generation of crops are defined as 1% of y dimension, and second generation as 2%. We add some margin, and deciding on 3%. 

We define maximum subtasks as:

<a href="https://www.codecogs.com/eqnedit.php?latex=\frac{y}{max(3\%&space;*&space;y,&space;8&space;&plus;&space;2\%&space;*&space;y)}&space;*&space;frames" target="_blank"><img src="https://latex.codecogs.com/gif.latex?\frac{y}{max(3\%&space;*&space;y,&space;8&space;&plus;&space;2\%&space;*&space;y)}&space;*&space;frames" title="\frac{y}{max(3\% * y, 8 + 2\% * y)} * frames" /></a>

This reduces to:

<a href="https://www.codecogs.com/eqnedit.php?latex=\frac{frames}{max(3\%,&space;\frac{8}{y}&space;&plus;&space;2\%)}" target="_blank"><img src="https://latex.codecogs.com/gif.latex?\frac{frames}{max(3\%,&space;\frac{8}{y}&space;&plus;&space;2\%)}" title="\frac{frames}{max(3\%, \frac{8}{y} + 2\%)}" /></a>

So we are ensuring that subtasks is at least 8px/y + 2%, this will grow to 800px linear, and then stop. Yielding 33 subtasks per frame

**Comment by badb** [comment]
We can assume that high quality production frames can take ~ 40 hours of rendering. 
From PBRT book: 

> Final rendering of the cover image at 1496 by 2235 resolution using pbrt took over 40 hours of computation on an eight-core Mac Pro computer.

This gives around ~1 h 15 minutes for single subtask which is very reasonable. So setting maximum 33 subtasks per frame seems to be a good choice!
