### ISSUE TITLE
Default working dir for GNR is `None`.

### ISSUE THREAD

**Issue by chfast** [golemfactory/clay#70]

**Comment by badb** [comment]
default dir should be DEFAULT_ROOT_PATH = os.environ.get('GOLEM'). Can you please check it on Linux after configuration changes from this [pull request](https://github.com/imapp-pl/golem/pull/68)?

Anyway, it should be always corrected to absolute path, so that's the first thing that must be corrected. 
Secondly, where do we want to put this file when we remove GOLEM variable? In AppData?
